export const translations = {
  en: {
    appName: "DiDiT",
    tagline: "The friction-free way to build habits",
    nav: {
      support: "Support",
      privacy: "Privacy Policy",
      terms: "Terms of Service",
    },
    support: {
      title: "Support",
      contactTitle: "Contact Us",
      contactDesc: "If you have any questions while using the app, please contact us:",
      email: "Email: ",
      faqTitle: "FAQ",
      faqs: [
        {
          q: "How does DiDiT generate content?",
          a: "DiDiT uses a pre-prepared 'Quotes' library. These sentences were generated by AI models and embedded in the app. The app randomly displays these fixed quotes in rotation, providing you with daily inspiration.",
        },
        {
          q: "Does the app require internet?",
          a: "No. DiDiT works completely offline. All quotes are built into the app and can be used without an internet connection.",
        },
        {
          q: "Will the quotes be updated?",
          a: "Quote content is updated with app updates. New versions may add new quotes to bring you more diverse inspirational content.",
        },
      ],
    },
    privacy: {
      title: "Privacy Policy",
      lastUpdated: "Last updated: January 2026",
      dataCollection: "Data Collection",
      dataCollectionDesc: "DiDiT is an offline app and we take your privacy seriously.",
      dataCollectionList: [
        "We do not collect, store, or upload any of your personal data",
        "The app runs completely offline and does not communicate with any servers",
        "All quote content is built into the app and can be used without internet",
      ],
      localStorage: "Local Storage",
      localStorageDesc: "DiDiT does not collect any user data. All content needed for the app to run is built-in and does not involve any local file storage or data reading.",
      contact: "Contact Us",
      contactDesc: "If you have any questions about the privacy policy, please contact us at ",
    },
    terms: {
      title: "Terms of Service",
      lastUpdated: "Last updated: January 2026",
      license: "License",
      licenseDesc: "DiDiT is free software. You may use it for personal or commercial purposes without any charge.",
      disclaimer: "Disclaimer",
      disclaimerList: [
        "DiDiT is provided 'as is' without any express or implied warranties",
        "We do not guarantee the accuracy, completeness, or reliability of the content",
        "You bear the risk of using the content generated by the app",
      ],
      limitation: "Limitation of Liability",
      limitationDesc: "In no event shall the developers of DiDiT be liable for any direct, indirect, incidental, special, or consequential damages arising out of or related to the use of this software.",
    },
    footer: "© 2026 DiDiT. All rights reserved.",
    language: "Language",
  },
  zh: {
    appName: "DiDiT",
    tagline: "拒绝精神内耗，回归习惯本质",
    nav: {
      support: "技术支持",
      privacy: "隐私政策",
      terms: "服务条款",
    },
    support: {
      title: "技术支持",
      contactTitle: "联系我们",
      contactDesc: "如果您在使用过程中遇到任何问题，请通过以下方式联系我们：",
      email: "电子邮件：",
      faqTitle: "常见问题",
      faqs: [
        {
          q: "DiDiT 是如何生成内容的？",
          a: "DiDiT 使用预先准备好的「金句」库，这些句子由 AI 模型生成后固化在应用中。应用会在这些固定句子中循环随机展示，为您提供每日励志和启发内容。",
        },
        {
          q: "应用是否需要联网？",
          a: "不需要。DiDiT 完全离线工作，所有金句都已内置在应用中，无需网络连接即可使用。",
        },
        {
          q: "金句内容会更新吗？",
          a: "金句内容会在应用更新时同步更新。新版本可能会添加新的句子，为您带来更多样的启发内容。",
        },
      ],
    },
    privacy: {
      title: "隐私政策",
      lastUpdated: "最后更新日期：2026年1月",
      dataCollection: "数据收集",
      dataCollectionDesc: "DiDiT 是一款离线应用，我们非常重视您的隐私。",
      dataCollectionList: [
        "我们不会收集、存储或上传您的任何个人数据",
        "应用完全离线运行，不与任何服务器通信",
        "所有金句内容已内置在应用中，无需联网即可使用",
      ],
      localStorage: "本地存储",
      localStorageDesc: "DiDiT 不收集任何用户数据。应用运行所需的全部内容都已内置，不涉及任何本地文件存储或数据读取。",
      contact: "联系我们",
      contactDesc: "如果您对隐私政策有任何疑问，请通过 ",
    },
    terms: {
      title: "服务条款",
      lastUpdated: "最后更新日期：2026年1月",
      license: "使用许可",
      licenseDesc: "DiDiT 是一款免费软件，您可以在个人或商业用途中使用它，无需支付任何费用。",
      disclaimer: "免责声明",
      disclaimerList: [
        "DiDiT 按「原样」提供，不提供任何明示或暗示的保证",
        "我们不保证应用生成内容的准确性、完整性或可靠性",
        "使用应用产生的内容由您自行承担风险",
      ],
      limitation: "责任限制",
      limitationDesc: "在任何情况下，DiDiT 的开发者均不对因使用或无法使用本软件而导致的任何直接、间接、附带、特殊或后果性损害承担责任。",
    },
    footer: "© 2026 DiDiT. 保留所有权利。",
    language: "语言",
  },
};
